import { Router } from 'express';
import { sendSuccess, sendError } from '../middleware/envelope.js';
import {
  A2UISurfaceSchema,
  A2UIComponentSchema,
  A2UICardPropsSchema,
  A2UIComparisonPanelPropsSchema,
  A2UIEvidencePanelPropsSchema,
  A2UIApprovalPanelPropsSchema
} from '@arc/domain-core';

export const a2uiRouter = Router();

// 1. GET /api/v1/a2ui/templates - Standard Controlled Component Vocabulary Templates
a2uiRouter.get('/a2ui/templates', async (_req, res, next) => {
  try {
    const templates = [
      {
        id: 'tars_ambiguity_review',
        title: 'TARS 2.0 Indirect Tax Ambiguity Review',
        description: 'Generated by TARS Matching Agent & Tax Policy Agent when candidate invoice pairs have variance within statutory thresholds.',
        surface: {
          surfaceId: 'surf_tars_ambiguity_0984',
          title: 'Vendor Invoice Ambiguity Review — Section 16(2) Exemption Check',
          description: 'Discrepancy detected between GSTR-2B government filing and internal SAP purchase register.',
          components: [
            {
              type: 'Card',
              id: 'card_summary',
              props: {
                title: 'GST Inward Tax Credit Summary',
                status: 'WARNING',
                metrics: [
                  { label: 'Reconciled Value', value: '$1,452,900.00' },
                  { label: 'Ambiguous Candidate', value: '$24,500.00' },
                  { label: 'Discrepancy Variance', value: '$0.04' },
                  { label: 'Potential Tax Exposure', value: '$0.00 (Protected)' }
                ]
              }
            },
            {
              type: 'ComparisonPanel',
              id: 'comp_invoice_pairs',
              props: {
                title: 'Side-by-Side Record Ambiguity Comparison',
                leftEntity: {
                  title: 'GST Portal Official Record (GSTR-2B)',
                  fields: {
                    'Supplier GSTIN': '27AAACG0564K1Z2',
                    'Vendor Legal Name': 'Reliance Retail Digital Logistics Ltd',
                    'Invoice No': 'INV-2026-0984',
                    'Invoice Date': '2026-08-28',
                    'Taxable Amount': '$24,500.00',
                    'IGST Amount': '$4,410.00',
                    'Filing Status': 'FILED_ON_TIME'
                  }
                },
                rightEntity: {
                  title: 'ERP Purchase Register (SAP ECC)',
                  fields: {
                    'Supplier GSTIN': '27AAACG0564K1Z2',
                    'Vendor Legal Name': 'Reliance Retail Digital Logistics Ltd',
                    'Invoice No': 'INV/2026/984',
                    'Invoice Date': '2026-08-30',
                    'Taxable Amount': '$24,500.00',
                    'IGST Amount': '$4,410.04',
                    'Entry Status': 'POSTED_PENDING_RECON'
                  }
                },
                discrepancies: [
                  { field: 'Invoice No', reason: 'Syntactic punctuation variance (hyphen vs slash separator)', severity: 'LOW' },
                  { field: 'Invoice Date', reason: '2-day delivery transit timing variance', severity: 'LOW' },
                  { field: 'IGST Amount', reason: '$0.04 rounding tolerance variance under Section 16(2)', severity: 'LOW' }
                ]
              }
            },
            {
              type: 'EvidencePanel',
              id: 'evid_legal_citation',
              props: {
                title: 'Authoritative KPMG Policy Admissibility Evidence',
                policyName: 'KPMG Indirect Tax Policy v12 — Statutory Section 16(2)',
                recommendation: 'PERMISSIBLE_WITH_AUDITOR_SIGNOFF',
                confidenceScore: 0.98,
                clauses: [
                  {
                    clauseId: 'SEC_16_2_TIMING',
                    text: 'Invoice date discrepancies under 30 calendar days are statutory-compliant provided the supplier has remitted tax liability in GSTR-1 and GSTR-3B.'
                  },
                  {
                    clauseId: 'CIRCULAR_183_ROUNDING',
                    text: 'Numeric rounding variances under INR 1.00 ($0.05 equivalent) shall be treated as matched pairs without tax credit reversal.'
                  }
                ]
              }
            },
            {
              type: 'ApprovalPanel',
              id: 'appr_human_action',
              props: {
                actions: [
                  { id: 'APPROVE', label: 'Approve & Claim Full Credit ($4,410.00)', variant: 'PRIMARY' },
                  { id: 'REQUEST_DOCS', label: 'Request Vendor E-Way Bill Proof', variant: 'SECONDARY' },
                  { id: 'REJECT', label: 'Disallow ITC & Escalate to Audit', variant: 'DANGER' }
                ],
                requireComment: true,
                resumeToken: 'res_tok_demo_a2ui_surface'
              }
            }
          ]
        }
      },
      {
        id: 'statutory_policy_audit',
        title: 'Statutory Policy Audit & Legal Provenance',
        description: 'Authoritative legal citation verification panel with cryptographic document hash.',
        surface: {
          surfaceId: 'surf_statutory_audit',
          title: 'Statutory Compliance Audit Evidence Dossier',
          components: [
            {
              type: 'Card',
              id: 'card_policy_meta',
              props: {
                title: 'Policy Authority Dossier',
                status: 'SUCCESS',
                metrics: [
                  { label: 'Policy Name', value: 'KPMG Indirect Tax Advisory v12' },
                  { label: 'Jurisdiction', value: 'India GST & State SGST' },
                  { label: 'Effective Date', value: '2026-04-01' },
                  { label: 'Document Hash', value: 'sha256:4a8b...19e0' }
                ]
              }
            },
            {
              type: 'EvidencePanel',
              id: 'evid_sec16',
              props: {
                title: 'Section 16(2) Statutory Condition Checks',
                policyName: 'Central Goods and Services Tax Act 2017',
                recommendation: 'FULLY_COMPLIANT',
                confidenceScore: 0.99,
                clauses: [
                  {
                    clauseId: 'CONDITION_A_TAX_INVOICE',
                    text: 'Registered person is in possession of a tax invoice or debit note issued by a registered supplier.'
                  },
                  {
                    clauseId: 'CONDITION_B_RECEIPT_OF_GOODS',
                    text: 'Registered person has received the goods or services or both with physical delivery proof.'
                  },
                  {
                    clauseId: 'CONDITION_C_TAX_PAID_TO_GOVT',
                    text: 'Tax charged in respect of supply has been actually paid to the Government credit via electronic cash or credit ledger.'
                  }
                ]
              }
            }
          ]
        }
      }
    ];

    sendSuccess(res, templates);
  } catch (error) {
    next(error);
  }
});

// 2. POST /api/v1/a2ui/validate - Strict Zod Validation of A2UI JSON Surface
a2uiRouter.post('/a2ui/validate', async (req, res, next) => {
  try {
    const parsed = A2UISurfaceSchema.parse(req.body);

    // Validate individual component props strictly
    for (const comp of parsed.components) {
      if (comp.type === 'Card') {
        A2UICardPropsSchema.parse(comp.props);
      } else if (comp.type === 'ComparisonPanel') {
        A2UIComparisonPanelPropsSchema.parse(comp.props);
      } else if (comp.type === 'EvidencePanel') {
        A2UIEvidencePanelPropsSchema.parse(comp.props);
      } else if (comp.type === 'ApprovalPanel') {
        A2UIApprovalPanelPropsSchema.parse(comp.props);
      }
    }

    sendSuccess(res, {
      valid: true,
      componentCount: parsed.components.length,
      surfaceId: parsed.surfaceId,
      message: 'A2UI Surface payload strictly conforms to Controlled Component Vocabulary schema.'
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      valid: false,
      error: {
        code: 'SCHEMA_VALIDATION_ERROR',
        message: error.errors ? error.errors.map((e: any) => `${e.path.join('.')}: ${e.message}`).join(', ') : error.message
      }
    });
  }
});
